### PR TITLE
chore: initial project roadmap

### PR DESCRIPTION
**Pull request by jpower432**
Signed-off-by: Jennifer Power <barnabei.jennifer@gmail.com>

### CODE REVIEW

**Review by afflom — APPROVED** [review]
Thank you for getting this out there.

**Comment by afflom** [comment]
@sabre1041 @usrbinkat @d10n Can you please give this a look?

**Comment by afflom** [comment]
Imo, they should be public.

**Comment by usrbinkat** [comment]
@afflom this is good content.

I'd like to wire frame the website content, then graph it back to different github projects and repos. I'm not sure yet whether this repo should even exist or what it's purpose is, to know whether your PR belongs here.

Right now I'm un-sure what content belongs where between the following:

**uor-framework/uor-framework
uor-framework/.github/README.md
uor-framework/samples
uor-framework/examples
uor-framework/universalreference.io
uor-community/***

**Comment by jpower432** [comment]
Closing. Roadmap information will be communicate in blog form on the emporous.io website.

**Pull request closed without merging**
